# Generated by Django 3.2 on 2021-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('forename', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('postcode', models.CharField(max_length=10)),
                ('items', models.CharField(max_length=5)),
                ('con_number', models.CharField(max_length=30)),
                ('deliverycompany', models.CharField(max_length=60)),
            ],
        ),
    ]
